def remove = [
    item('appliedenergistics2:inscriber'),
    item('avaritia:resource', 1),
    item('immersiveengineering:metal_decoration0', 3),
    item('immersiveengineering:stone_decoration', 10),
    item('immersiveengineering:metal_decoration0', 4),
    item('immersiveengineering:metal_decoration0', 5),
    item('immersiveengineering:stone_decoration'),
    item('bloodmagic:soul_forge'),
    item('mekanism:basicblock', 8),
    item('draconicevolution:draconic_core'),
    item('meem:blockhighprecisionassembler'),
    item('extrautils2:resonator'),
    item('bloodmagic:altar'),
    item('stevescarts:modulecomponents', 45),
    item('omegacraft:machine_workbenchb'),
    item('rftools:machine_frame'),
    item('aetherworks:forge_component', 4),
    item('storagenetwork:kabel'),
    item('tce:tce_bindingelement'),
    item('stevescarts:modulecomponents', 18),
    item('planttech2:plantium_ingot'),
    item('woot:yahhammer'),
    item('nuclearcraft:part', 9),
    item('thermalexpansion:frame'),
    item('thermalexpansion:frame', 64),
    item('thermalexpansion:frame', 128),
    item('astralsorcery:blockaltar'),
    item('botania:altar'),
    item('refraction:reflective_alloy'),
    item('integrateddynamics:variable'),
    item('nuclearcraft:part', 4),
    item('nuclearcraft:part', 7),
    item('compactmachines3:fieldprojector'),
    item('nuclearcraft:part', 10),
    item('extrautils2:machine')
    ]
for(part in remove) {
    crafting.removeByOutput(part)
}