name: "手動: バージョンを特定の値に変更"

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'バージョン'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: nodeをセットアップ
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4
    
    - name: Commiterを設定
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: バージョンを書き換え
      run: |
        node internal/set-pack-version.js ${{ github.event.inputs.tag }}
      shell: bash
    
    - name: コミットしプッシュ
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add manifest.json
        git commit -m 'パックバージョンを${{ github.event.inputs.tag }}に変更'
        git push
